services:
  - type: web
    name: bybit-p2p-telegram-bot
    runtime: python
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
